/*
 Copyright and licenses see https://www.dynatrace.com/company/trust-center/customers/reports/*/
(function jq(){function $a(K,A){return Ca(K)&&"href"===A?1:ta(K)&&"value"===A?32:ma.vf.some(function(M){return M.test(A)})?16:Pa(K)&&"value"===A?2===cb(K)?16:1:1}function cb(K){if(Ya(K)||Ya(K.parentNode))return 1;Za.has(K)&&db.set(K,db.get(K)|8);Ja.has(K)&&db.set(K,db.get(K)|2);oa.has(K)&&(ma.uc?ub.set(K,ub.get(K)|1):ub.set(K,ub.get(K)|4));ba(K)&&K.hasAttribute("data-dtrum-mask")&&(Na(K)?ub.set(K,ub.get(K)|4):db.set(K,db.get(K)|10));if(db.has(K))return db.get(K);if(ub.has(K))return ub.get(K);var A=
K,M=!1;A.nodeType===Node.TEXT_NODE&&(A=A.parentNode,M=!0);var Ga=Na(A);var Wa=M;void 0===Wa&&(Wa=!1);Wa=!Ga||Wa||"OPTION"===A.nodeName?(Ga?ub:db).get(Wa?A:A.parentNode):void 0;var xb=void 0;Ga&&fb(ma.Ec,A)&&(xb|=4);!Ga&&fb(ma.zc,A)&&(xb|=2);!Ga&&fb(ma.Kc,A)&&(xb|=8);if(xb||Ga)a:if(Ga=void 0===Ga?!1:Ga,M=void 0===M?!1:M,!Ga&&xb)Wa=xb;else{if(Ga){xb=xb&&!(xb&1)||ma.uc?(!xb||xb&1)&&ma.uc||xb&&!(xb&1)&&!ma.uc?A.parentNode&&Na(A.parentNode)?Wa&&!(Wa&1):!0:!1:Wa&&!(Wa&1);if(M&&xb){Wa=Wa?Wa:2;break a}if(xb){Wa=
fb(P,A)||A instanceof HTMLFormElement&&"text"===A.type?4:8;break a}}Wa=1}else Wa=Wa?Wa:1;Na(K)?ub.set(K,ub.get(K)|Wa):db.set(K,db.get(K)|Wa);return Wa}function fb(K,A){for(var M=0;M<K.length;M++)if(Td.matchesSelector(A,K[M]))return!0;return!1}function La(K,A){K.forEach(function(M){[].slice.call(document.querySelectorAll(M)).forEach(function(Ga){A.has(Ga)||A.set(Ga,M)})})}function Na(K){return Pa(K)?!1:-1!==t.indexOf(K.nodeName)}function Pa(K){return K&&"INPUT"===K.nodeName?(K=K.getAttribute("type"))?
-1!==C.indexOf(K.toLowerCase()):!1:!1}function Ca(K){return ba(K)&&"link"===K.nodeName.toLowerCase()}function Ya(K){return ba(K)&&"style"===K.nodeName.toLowerCase()}function ba(K){return K&&K.nodeType&&1===K.nodeType}function ta(K){return K&&"INPUT"===K.nodeName&&"password"===K.type.toLowerCase()}function bb(){bb=Object.assign||function(K){for(var A,M=1,Ga=arguments.length;M<Ga;M++){A=arguments[M];for(var Wa in A)Object.prototype.hasOwnProperty.call(A,Wa)&&(K[Wa]=A[Wa])}return K};return bb.apply(this,
arguments)}function ab(K,A,M,Ga){if(A&&"object"===typeof A||"function"===typeof A)for(var Wa=Ib(A),xb=0,Nb=Wa.length,Xb;xb<Nb;xb++)Xb=Wa[xb],yb.call(K,Xb)||Xb===M||Eb(K,Xb,{get:function(cc){return A[cc]}.bind(null,Xb),enumerable:!(Ga=Ka(A,Xb))||Ga.enumerable});return K}function ya(K,A,M,Ga){function Wa(xb){return xb instanceof M?xb:new M(function(Nb){Nb(xb)})}return new (M||(M=Oa))(function(xb,Nb){function Xb(Dc){try{dc(Ga.next(Dc))}catch(xd){Nb(xd)}}function cc(Dc){try{dc(Ga["throw"](Dc))}catch(xd){Nb(xd)}}
function dc(Dc){Dc.done?xb(Dc.value):Wa(Dc.value).then(Xb,cc)}dc((Ga=Ga.apply(K,A||[])).next())})}function eb(K,A){function M(dc){return function(Dc){return Ga([dc,Dc])}}function Ga(dc){if(xb)throw new TypeError("Generator is already executing.");for(;Wa;)try{if(xb=1,Nb&&(Xb=dc[0]&2?Nb["return"]:dc[0]?Nb["throw"]||((Xb=Nb["return"])&&Xb.call(Nb),0):Nb.next)&&!(Xb=Xb.call(Nb,dc[1])).done)return Xb;if(Nb=0,Xb)dc=[dc[0]&2,Xb.value];switch(dc[0]){case 0:case 1:Xb=dc;break;case 4:return Wa.label++,{value:dc[1],
done:!1};case 5:Wa.label++;Nb=dc[1];dc=[0];continue;case 7:dc=Wa.Ja.pop();Wa.ia.pop();continue;default:if(!(Xb=Wa.ia,Xb=0<Xb.length&&Xb[Xb.length-1])&&(6===dc[0]||2===dc[0])){Wa=0;continue}if(3===dc[0]&&(!Xb||dc[1]>Xb[0]&&dc[1]<Xb[3]))Wa.label=dc[1];else if(6===dc[0]&&Wa.label<Xb[1])Wa.label=Xb[1],Xb=dc;else if(Xb&&Wa.label<Xb[2])Wa.label=Xb[2],Wa.Ja.push(dc);else{Xb[2]&&Wa.Ja.pop();Wa.ia.pop();continue}}dc=A.call(K,Wa)}catch(Dc){dc=[6,Dc],Nb=0}finally{xb=Xb=0}if(dc[0]&5)throw dc[1];return{value:dc[0]?
dc[1]:void 0,done:!0}}var Wa={label:0,J:function(){if(Xb[0]&1)throw Xb[1];return Xb[1]},ia:[],Ja:[]},xb,Nb,Xb,cc;return cc={next:M(0),"throw":M(1),"return":M(2)},"function"===typeof Symbol&&(cc[Symbol.iterator]=function(){return this}),cc}function T(K,A,M){if(M||2===arguments.length)for(var Ga=0,Wa=A.length,xb;Ga<Wa;Ga++)!xb&&Ga in A||(xb||(xb=Array.prototype.slice.call(A,0,Ga)),xb[Ga]=A[Ga]);return K.concat(xb||Array.prototype.slice.call(A))}function N(){}function D(K,A){return function(){K.apply(A,
arguments)}}function W(K){if(!(this instanceof W))throw new TypeError("Promises must be constructed via new");if("function"!==typeof K)throw new TypeError("not a function");this.ka=0;this.pc=!1;this.sa=void 0;this.Ha=[];F(K,this)}function fa(K,A){for(;3===K.ka;)K=K.sa;0===K.ka?K.Ha.push(A):(K.pc=!0,W.Kb(function(){var M=1===K.ka?A.ze:A.Ae;if(null===M)(1===K.ka?ra:pa)(A.promise,K.sa);else{try{var Ga=M(K.sa)}catch(Wa){pa(A.promise,Wa);return}ra(A.promise,Ga)}}))}function ra(K,A){try{if(A===K)throw new TypeError("A promise cannot be resolved with itself.");
if(A&&("object"===typeof A||"function"===typeof A)){var M=A.then;if(A instanceof W){K.ka=3;K.sa=A;G(K);return}if("function"===typeof M){F(D(M,A),K);return}}K.ka=1;K.sa=A;G(K)}catch(Ga){pa(K,Ga)}}function pa(K,A){K.ka=2;K.sa=A;G(K)}function G(K){2===K.ka&&0===K.Ha.length&&W.Kb(function(){K.pc||W.Rc(K.sa)});for(var A=0,M=K.Ha.length;A<M;A++)fa(K,K.Ha[A]);K.Ha=null}function B(K,A,M){this.ze="function"===typeof K?K:null;this.Ae="function"===typeof A?A:null;this.promise=M}function F(K,A){var M=!1;try{K(function(Ga){M||
(M=!0,ra(A,Ga))},function(Ga){M||(M=!0,pa(A,Ga))})}catch(Ga){M||(M=!0,pa(A,Ga))}}function S(){return"undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope}function na(){if(S())return!1;if(ed.dT_.bcv("srif")){var K=Rc;return!(K===K.top||!K.parent.dT_)}try{return Rc!==Rc.top}catch(A){return!0}}function X(K,A){return-1!==K.indexOf(A)}function va(K,A,M){if(K.forEach)K.forEach(A,M);else for(var Ga=0;Ga<K.length;Ga++)A.call(M,K[Ga],Ga,K)}function Ea(K){var A=Fc;Vc.set(A,K);setTimeout(function(){Vc["delete"](A)},
1E3);Fc++;return new ad({da:"pair",query:"pair-id",result:A})}function Ta(K){ae&&(Oc.Ze(self,ae),ae=null);return new Oa(function(A){ae=Oc.oe(self,function(M,Ga,Wa){"pair"===M.da&&"pair-id"===M.query&&(K.send(new ad({da:"pair",query:"pair-ack",result:M.result})),Wa(),A())});K.send(new ad({da:"pair",query:"pair-req"}))})}function Gb(K){return new Oa(function(A){K.Mc(function(M){if("pair"===M.da&&X(["pair-req","pair-ack"],M.query))if("pair-ack"===M.query&&"number"===typeof M.result)(M=Vc.get(M.result))&&
A(M);else for(Oc.Pc(self,Ea(self)),M=0;M<Rc.frames.length;M++)Oc.Pc(Rc.frames[M],Ea(Rc.frames[M]))})})}function mb(K){return new Oa(function(A){K.Mc(function(M){"handshake"===M.da&&X(["connect-ack","connect-pair"],M.query)&&A({wh:"connect-pair"===M.query})})})}function ca(K){return new Oa(function(A,M){setTimeout(M,K)})}function H(K){return ya(this,void 0,void 0,function(){var A,M,Ga;return eb(this,function(Wa){switch(Wa.label){case 0:A=new ad({da:"handshake",query:"connect-req"}),M=new Oc,Oc.Pc(K,
A,{gf:[M.Eh]}),Wa.label=1;case 1:return Wa.ia.push([1,5,,6]),[4,Oa.race([mb(M),ca(1E3)])];case 2:return(Ga=Wa.J())&&Ga.wh?[4,Oa.race([Ta(M),ca(1E3)])]:[3,4];case 3:Wa.J(),Wa.label=4;case 4:return[3,6];case 5:throw Wa.J(),M.port.close(),Error("timeout");case 6:return[2,M]}})})}function Ba(K,A){void 0===A&&(A=15);return ya(this,void 0,void 0,function(){var M;return eb(this,function(Ga){switch(Ga.label){case 0:M=0,Ga.label=1;case 1:if(!(M<A))return[3,6];Ga.label=2;case 2:return Ga.ia.push([2,4,,5]),
[4,H(K)];case 3:return[2,Ga.J()];case 4:return Ga.J(),M++,[3,5];case 5:return[3,1];case 6:throw Error("connect handshake failed");}})})}function xa(K,A){Oc.oe(K,function(M,Ga){return ya(this,void 0,void 0,function(){var Wa,xb,Nb,Xb;return eb(this,function(cc){switch(cc.label){case 0:if("handshake"!==M.da||"connect-req"!==M.query)return[2];Wa=-1<Object.prototype.toString.call(K).indexOf("Worker")?K:Ga.source;xb="undefined"===typeof Wa;Nb=Ga.ports[0];Xb=new Oc(Nb);Xb.send(new ad({da:"handshake",query:xb?
"connect-pair":"connect-ack"}));if(!xb)return[3,4];cc.label=1;case 1:return cc.ia.push([1,3,,4]),[4,Gb(Xb)];case 2:return Wa=cc.J(),[3,4];case 3:return cc.J(),[3,4];case 4:return Wa&&A(Wa,Xb),[2]}})})})}function Ua(K){for(var A=[],M=1;M<arguments.length;M++)A[M-1]=arguments[M];try{JSON.stringify(A)}catch(Ga){}}function sb(K,A,M){return ya(this,void 0,void 0,function(){var Ga,Wa,xb,Nb,Xb,cc,dc;return eb(this,function(Dc){switch(Dc.label){case 0:if("undefined"===typeof M.result)return[3,1];Ga=(Ic.get(M.id)||
{}).resolve;Ic["delete"](M.id);if(!Ga)return Ua("Resolver not found for message",M),[2];Ga(M.result);return[3,5];case 1:if(!Sc.has(M.da))return[3,4];Wa=Sc.get(M.da);xb=X(ec,Wa);return Wa?[4,Wa.apply(A,T([K],M.query,!0))]:[3,3];case 2:Nb=Dc.J(),Xb=xb?Nb:[Nb,[]],cc=Xb[0],dc=Xb[1],M.Kh(cc),A.send(M,dc),Dc.label=3;case 3:return[3,5];case 4:Ua("Invalid Protocol Message",M),Dc.label=5;case 5:return[2]}})})}function nb(){Qc=new Map;Ic=new Map;Sc=new Map;Vc=new Map}function kb(K){K=void 0===K?{}:K;var A=
K.Ri,M=void 0===A?void 0:A;K=K.xi;var Ga=void 0===K?!1:K;return ya(this,void 0,void 0,function(){var Wa,xb;return eb(this,function(Nb){switch(Nb.label){case 0:nb();if(!(S()||na()||Ga))return[3,4];Wa=na()?self.parent:self;Nb.label=1;case 1:return Nb.ia.push([1,3,,4]),[4,Ba(Wa)];case 2:return xb=Nb.J(),Qc.set(Wa,xb),xb.Mc(function(Xb){sb(Wa,xb,Xb)}),[3,4];case 3:return Nb.J(),[2,!1];case 4:return M?[4,new Oa(function(Xb){xa(M,function(cc,dc){Qc.set(cc,dc);dc.Mc(function(Dc){sb(cc,dc,Dc)});Xb()})})]:
[3,6];case 5:Nb.J(),Nb.label=6;case 6:return S()||Ga||xa(self,function(Xb,cc){Qc.set(Xb,cc);cc.Mc(function(dc){sb(Xb,cc,dc)})}),[2,!0]}})})}function Bb(K,A,M){M=(void 0===M?{}:M).gf;M=void 0===M?!1:M;Qc&&Ic&&Sc||nb();Sc.set(K,A);M&&ec.push(A)}function tc(K,A,M){var Ga=new ad({da:A,query:M});return new Oa(function(Wa,xb){Ic.set(Ga.id,{resolve:Wa,reject:xb});K.send(Ga)})}function Sb(K){for(var A=[],M=1;M<arguments.length;M++)A[M-1]=arguments[M];Qc&&Ic&&Sc||nb();M=Qc.get(self);return M?tc(M,K,A):(Ua("sendQueryToMainThread - Channel not found for query",
K,A),Oa.resolve())}function Kb(){var K=Rc.dT_,A=K&&K.iIO;K=new MessageChannel;var M=K.port1,Ga=K.port2,Wa=new ArrayBuffer(1);return new Oa(function(xb){M.onmessage=function(Nb){Nb=Nb.data;xb(A?A(Nb,26):Nb instanceof ArrayBuffer);M.close()};Ga.postMessage(Wa,[Wa])})}function Ia(K){return Cc.get(K)}function Cb(){Cc.clear();he=[];bd.clear()}function Lb(){var K=[];bd.forEach(function(A){K.push(A)});return K}function Db(K,A){return K.find(A,void 0,!0).values.filter(function(M){return M}).map(Ia).filter(function(M){return void 0!==
M})}function aa(K,A,M){if(K.Ve()<A.from)return null;K=K.find(A,M);return 0===K.values.length?null:K}function y(K,A,M){if(K.uf<A.from)return null;var Ga=[];va(K.attributes,function(Wa){if(!(Wa.$c<A.from)){var xb=aa(Wa.values,A,M);xb&&Ga.push({name:Wa.name,entries:xb})}});return 0===Ga.length?null:Ga}function da(K,A){K.values.clear(A);K.Od.clear(A);K.od.clear(A);K.Ng.clear(A);K.Lf.clear(A);K.attributes.forEach(function(M){M.values.clear(A)})}function Ha(){return Math.round(fd+Me.now())}function Ra(K){var A,
M;Sb("perfstart",(A={},A.i="compress",A.t=Ha(),A.m="start",A));var Ga=new pe.Vi(K);A=new Uint8Array(Ga.Uj());Ga=Ga.jj(A);Sb("perfend",(M={},M.i="compress",M.t=Ha(),M.m="end",M.d=[["in",K.byteLength],["out",Ga]],M.a=!0,M));return A.buffer.slice(0,Ga)}function ob(K,A){K=Ra(A);return new Uint8Array(K)}function Ob(K){var A=String(K);we.forEach(function(M){A=A.replace(M[0],"\x00"+M[1])});return A}function Rb(K){try{if(zc.TextEncoder)return(new zc.TextEncoder).encode(K)}catch(Wa){}for(var A=[],M=0;M<K.length;M++){var Ga=
K.charCodeAt(M);128>Ga?A.push(Ga):2048>Ga?(A.push(Ga>>6|192),A.push(Ga&63|128)):55296===(Ga&64512)&&M+1<K.length&&56320===(K.charCodeAt(M+1)&64512)?(Ga=65536+((Ga&1023)<<10)+(K.charCodeAt(++M)&1023),A.push(Ga>>18|240),A.push(Ga>>12&63|128),A.push(Ga>>6&63|128),A.push(Ga&63|128)):(A.push(Ga>>12|224),A.push(Ga>>6&63|128),A.push(Ga&63|128))}return A}function ic(K,A){var M,Ga;void 0===A&&(A=Pe);Sb("perfstart",(M={},M.i="serialize",M.t=Ha(),M.m="start",M));qe=qe||new Uint8Array(Rb("\u0001"));var Wa={entries:[],
size:0},xb=[Wa];K.forEach(function(Xb){var cc={ja:"",hc:""};cc.ja+=Xb.id+"\u0002";cc.ja=Xb.name?cc.ja+(Ob(Xb.name)+"\u0002"):cc.ja+"\u0002";Xb.type&&"html"!==Xb.type&&(cc.ja+=Ob(Xb.type));Xb.values&&ia(Xb.values,"\u0005",cc);Xb.attributes&&Fa(Xb.attributes,cc);Xb.Od&&ia(Xb.Od,"\u0011",cc);Xb.od&&ia(Xb.od,"\u0012",cc);Xb=new Uint8Array(Rb("".concat(cc.ja).concat("\u0001").concat(cc.hc.slice(0,-1))));cc=Xb.byteLength+qe.byteLength;0<Wa.size&&Wa.size+cc>A&&(Wa={entries:[],size:0},xb.push(Wa));Wa.entries.push(Xb);
Wa.size+=cc});var Nb=0;M=xb.map(function(Xb){var cc=new Uint8Array(Xb.size-qe.byteLength),dc=0;Xb.entries.forEach(function(Dc){cc.set(Dc,dc);dc+=Dc.byteLength;dc!==cc.byteLength&&(cc.set(qe,dc),dc+=qe.byteLength)});Nb+=cc.byteLength;return cc});Sb("perfend",(Ga={},Ga.i="serialize",Ga.t=Ha(),Ga.m="end",Ga.d=[["nodes",K.length],["out",Nb]],Ga.a=!0,Ga));return M}function ia(K,A,M){M.ja+=A;K.ef.forEach(function(Ga,Wa){var xb=K.values[Wa];M.hc+=Ga;"string"===typeof xb?""!==xb?M.ja+=Ob(xb):M.ja+="\u0003":
null===xb||"undefined"===typeof xb?M.ja+="\u0014":(M.ja+="\u0004",M.hc+="\u0002"+xb);Wa!==K.ef.length-1&&(M.ja+="\u0002");M.hc+="\u0002"})}function Fa(K,A){A.ja+="\u0006";K.forEach(function(M,Ga){A.ja+=Ob(M.name)+"\u0002";M.entries.ef.forEach(function(Wa,xb){A.hc+=Wa;Wa=M.entries.values[xb];"string"===typeof Wa?""!==Wa?A.ja+=Ob(Wa):A.ja+="\u0003":null===Wa||"undefined"===typeof Wa?A.ja+="\u0014":(A.ja+="\u0004",A.hc+="\u0002"+Wa);xb!==M.entries.ef.length-1&&(A.ja+="\u0002");A.hc+="\u0002"});Ga!==
K.length-1&&(A.ja+="\u0006")})}function O(K,A,M){for(var Ga=[];K.length;)K.splice(0,K.length).forEach(function(Wa){ja(Wa,Ga,A,function(xb){var Nb=A(xb.Lf);M(xb)&&K.unshift.apply(K,Nb)})})}function ja(K,A,M,Ga){K=[[K]];for(var Wa=new Set;K.length;){var xb=K.pop();if(xb){var Nb=xb.shift();if(void 0===Nb||X(A,Nb.id))xb.length&&K.push(xb);else{var Xb=Wa.has(Nb)?[]:M(Nb.od);Xb.length?(Wa.add(Nb),xb.push(Nb),K.push(xb),K.push(Xb)):(Wa["delete"](Nb),Nb.id&&A.push(Nb.id),xb.length&&K.push(xb),Ga(Nb))}}}}
function q(K){if(!(K.Aj()<be.from)){var A=K.Ig>=be.from,M=aa(K.values,be,Pe),Ga=y(K,be,Pe),Wa=aa(K.Od,be,Pe),xb=aa(K.od,be,Pe);if(A||M||Ga||Wa||xb)Ae.push({id:K.id,type:A?K.type:"html",name:A?K.name:void 0,values:M,attributes:Ga,Od:Wa,od:xb}),K.Zj()}}function I(K){if(K.$c<be.from)return!1;q(K);if("iframe"===K.name)return!1;da(K,be.Dg);return!0}function V(K,A){K=Ia("1");if(!K||K.Hg<.9*Pe&&A-hf<1E3*De)return[null,[]];hf=A;var M=[],Ga=[];va(he,function(Wa){var xb,Nb;Ae=[];var Xb=(Wa.yi||0)+1;be={from:Xb,
Dg:Math.max(A,Xb)};Sb("perfstart",(xb={},xb.i="collect",xb.t=Ha(),xb.m="start",xb));O([Wa],function(cc){return Db(cc,be)},I);Sb("perfend",(Nb={},Nb.i="collect",Nb.t=Ha(),Nb.m="end",Nb.d=[["nodes",Ae.length]],Nb.a=!0,Nb));Wa.yi=Math.min(Wa.$c,A-1);Lb().forEach(function(cc){cc.Ig>=Xb&&cc.Ig<=A&&q(cc)});0!==Ae.length&&ic(Ae).forEach(function(cc){cc=Ra(cc);Be&&Ga.push(cc);M.push({data:Be?cc:Array.prototype.slice.call(new Uint8Array(cc)),from:be.from,to:be.Dg})})});return 0===M.length?[null,[]]:[M,Ga]}
function L(){return ya(this,void 0,void 0,function(){return eb(this,function(K){switch(K.label){case 0:return hf=0,Bb("collectorConfig",function(A,M){Pe=M.maxSignalLength;De=M.transmissionDelay;pf=M.isEdgeOrIe;return M}),[4,Kb()];case 1:return Be=K.J(),Bb("collect",V,{gf:!0}),[2]}})})}function Y(K,A){void 0===A&&(A="*");return null!==K&&""!==K?K.replace(/[^- :\u2013\/\u2014._;,()=!?|<>+%\u20ac$\u00a2\u00a5\u00a3\u20bd\u5143\u20a8\u20bf'"@&\u3002\u3001\]\[\n\r\\]/g,A):K}function J(K){try{if(""===K)throw Error("Rule is an empty string");
Td.matchesSelector(document.documentElement,K);return!0}catch(A){return console.warn("Masking selector evaluation error: "+A.name,A),!1}}function Da(K){K.Ec=K.Ec.filter(function(A){return J(A)});K.zc=K.zc.filter(function(A){return J(A)});K.Kc=K.Kc.filter(function(A){return J(A)});return K}function ea(K){var A={uc:!0,Ec:[],zc:[],Kc:[],vf:[],version:"1"};if("undefined"===typeof K||""===K)return A;var M=decodeURIComponent(K).split(",");K=M[0];var Ga=M[1],Wa=M[2],xb=M[3];M=M[4];"1"===K&&(A.version=K);
if("1"===Ga||"0"===Ga)A.uc="1"===Ga;""!==Wa&&"undefined"!==typeof Wa&&(A.Ec=decodeURIComponent(Wa).split(";"));""!==xb&&"undefined"!==typeof xb&&(A.zc=decodeURIComponent(xb).split(";").map(function(Nb){Nb=Nb.split("&");var Xb=Nb[0];"undefined"!==typeof Nb[1]&&A.Kc.push(Xb);return Xb}));if(""!==M&&"undefined"!==typeof M)try{A.vf=decodeURIComponent(M).split(";").map(function(Nb){if(""===Nb)throw Error("RegExp rule is an empty string");return new RegExp(Nb)})}catch(Nb){console.warn("Masking attribute rule error: "+
Nb.name,Nb)}return Da(A)}function za(K){void 0===K&&(K=[]);var A=[];K.forEach(function(M){var Ga=M.split("/");M=Ga[1];Ga=Number(Ga[0]);try{if(0===Ga){var Wa=M.length-1,xb=M;M[Wa]===id.jf&&(xb=M.substr(0,Wa));Td.matchesSelector(document.documentElement,xb)}else 1===Ga&&new RegExp(M);A.push(Ze.create(Ga,M))}catch(Nb){}});return A}function Sa(K,A){K&&(A.prototype.toJSON=K)}function hb(K){var A=new Map,M=Date.prototype.toJSON;[Number,Boolean,String,Array,Object].forEach(function(Ga){A.set(Ga,Ga.prototype.toJSON);
delete Ga.prototype.toJSON});Date.prototype.toJSON=tg;try{return JSON.stringify(K)}finally{A.forEach(Sa),Date.prototype.toJSON=M}}function Fb(K){var A=[];K=Ia(K);if(!K)return[];O([K],function(M){return(M=Ia(M.dd()))?[M]:[]},function(M){M.id&&A.push(M.id);return!0});return A}function ac(K,A,M){K.forEach(function(Ga){(Ga=Ia(Ga))&&O([Ga],function(Wa){if(Wa=Wa.dd())if(Wa=Ia(Wa))return[Wa];return[]},function(Wa){if(Wa&&Wa.id)A["delete"](Wa.id);return!0})});A.forEach(function(Ga){if(Ga=Ia(Ga))Ga.Og(null,
M),Ga.vd(null,M),Ga.wd(null,M)})}function Vb(K,A){var M=Ff.decode(A);if(M&&M.size){var Ga=[],Wa=new Set;M.forEach(function(xb){if(!Ye[xb.type])return Ua("Invalid Mutation List operation: "+xb.type,{Ld:A});xb.type!==uf.Yh||void 0===xb.ga||Wa.has(xb.ga)||(Ga.push(xb.ga),Fb(xb.ga).forEach(function(Nb){Wa.add(Nb)}));return Ye[xb.type](xb,M.time)});ac(Ga,Wa,M.time)}else Ua("Invalid Mutation List query",{Ld:A})}function $b(K,A,M,Ga,Wa){for(var xb,Nb,Xb,cc,dc,Dc,xd,Yc,Gd,Tc,te;64<=Wa;){xb=A[0];Nb=A[1];Xb=
A[2];cc=A[3];dc=A[4];Dc=A[5];xd=A[6];Yc=A[7];for(Tc=0;16>Tc;Tc++)te=Ga+4*Tc,K[Tc]=(M[te]&255)<<24|(M[te+1]&255)<<16|(M[te+2]&255)<<8|M[te+3]&255;for(Tc=16;64>Tc;Tc++)Gd=K[Tc-2],te=(Gd>>>17|Gd<<15)^(Gd>>>19|Gd<<13)^Gd>>>10,Gd=K[Tc-15],Gd=(Gd>>>7|Gd<<25)^(Gd>>>18|Gd<<14)^Gd>>>3,K[Tc]=(te+K[Tc-7]|0)+(Gd+K[Tc-16]|0);for(Tc=0;64>Tc;Tc++)te=(((dc>>>6|dc<<26)^(dc>>>11|dc<<21)^(dc>>>25|dc<<7))+(dc&Dc^~dc&xd)|0)+(Yc+(vb[Tc]+K[Tc]|0)|0)|0,Gd=((xb>>>2|xb<<30)^(xb>>>13|xb<<19)^(xb>>>22|xb<<10))+(xb&Nb^xb&Xb^
Nb&Xb)|0,Yc=xd,xd=Dc,Dc=dc,dc=cc+te|0,cc=Xb,Xb=Nb,Nb=xb,xb=te+Gd|0;A[0]+=xb;A[1]+=Nb;A[2]+=Xb;A[3]+=cc;A[4]+=dc;A[5]+=Dc;A[6]+=xd;A[7]+=Yc;Ga+=64;Wa-=64}return Ga}function rc(K,A){try{return(new fe).update(A).digest()}catch(M){return null}}function Hc(K){return new Oa(function(A){setTimeout(A,K)})}function Zc(){return ya(this,void 0,void 0,function(){return eb(this,function(K){switch(K.label){case 0:return Bb("compress",ob),Bb("mutations",Vb),Bb("reset",Cb),Bb("SHA-256",rc),[4,L()];case 1:return K.J(),
[2]}})})}function ka(){return ya(this,void 0,void 0,function(){return eb(this,function(K){switch(K.label){case 0:return self.postMessage("loaded",void 0),[4,Hc(0)];case 1:return K.J(),[4,kb()];case 2:return K.J(),[4,Zc()];case 3:return K.J(),[2]}})})}function qa(){Oc.oe(self,function(K,A,M){return ya(this,void 0,void 0,function(){var Ga;return eb(this,function(Wa){switch(Wa.label){case 0:if("worker"!==K.da)return[2];Ga=K.query;switch(Ga){case "source":return[3,1];case "initialize":return[3,2];case "initialized":return[3,
5]}return[3,6];case 1:return Oc.Pc(self,new ad({da:"worker",query:"source",result:"(".concat("undefined"!==typeof jq&&jq.toString(),")();")})),[3,6];case 2:return[4,kb({xi:!0})];case 3:return Wa.J(),[4,Zc()];case 4:Wa.J(),Sb("workerLoaded"),Wa.label=5;case 5:M(),Wa.label=6;case 6:return[2]}})})})}var Oa=self.Promise,Ma=Object.create,Eb=Object.defineProperty,Ka=Object.getOwnPropertyDescriptor,Ib=Object.getOwnPropertyNames,Hb=Object.getPrototypeOf,yb=Object.prototype.hasOwnProperty,lc=function(K,A){return function(){return A||
(0,K[Ib(K)[0]])((A={exports:{}}).exports,A),A.exports}}({"../../node_modules/.pnpm/snappyjs@0.6.0/node_modules/snappyjs/snappy_compressor.js":function(K){function A(cc,dc){return 506832829*cc>>>dc}function M(cc,dc){return cc[dc]+(cc[dc+1]<<8)+(cc[dc+2]<<16)+(cc[dc+3]<<24)}function Ga(cc,dc,Dc){return cc[dc]===cc[Dc]&&cc[dc+1]===cc[Dc+1]&&cc[dc+2]===cc[Dc+2]&&cc[dc+3]===cc[Dc+3]}function Wa(cc,dc,Dc,xd,Yc){60>=Dc?(xd[Yc]=Dc-1<<2,Yc+=1):256>Dc?(xd[Yc]=240,xd[Yc+1]=Dc-1,Yc+=2):(xd[Yc]=244,xd[Yc+1]=Dc-
1&255,xd[Yc+2]=Dc-1>>>8,Yc+=3);var Gd=Yc,Tc;for(Tc=0;Tc<Dc;Tc++)xd[Gd+Tc]=cc[dc+Tc];return Yc+Dc}function xb(cc,dc,Dc,xd){if(12>xd&&2048>Dc)return cc[dc]=1+(xd-4<<2)+(Dc>>>8<<5),cc[dc+1]=Dc&255,dc+2;cc[dc]=2+(xd-1<<2);cc[dc+1]=Dc&255;cc[dc+2]=Dc>>>8;return dc+3}function Nb(cc){this.Zh=cc}var Xb=Array(15);Nb.prototype.Uj=function(){var cc=this.Zh.length;return 32+cc+Math.floor(cc/6)};Nb.prototype.jj=function(cc){var dc=this.Zh,Dc=dc.length,xd=0,Yc;var Gd=Dc;var Tc=0;do cc[Tc]=Gd&127,Gd>>>=7,0<Gd&&
(cc[Tc]+=128),Tc+=1;while(0<Gd);for(Yc=Tc;xd<Dc;){Gd=Math.min(Dc-xd,65536);var te=void 0;var $d,td;Tc=dc;var yd=xd;var Id=Gd;for(var Rg=cc,gd=Yc,pd=1;1<<pd<=Id&&14>=pd;)pd+=1;--pd;Yc=32-pd;"undefined"===typeof Xb[pd]&&(Xb[pd]=new Uint16Array(1<<pd));pd=Xb[pd];for(td=0;td<pd.length;td++)pd[td]=0;td=yd+Id;var Pd=yd;var Ud=yd;var ih=!0;if(15<=Id)for(Id=td-15,yd+=1,$d=A(M(Tc,yd),Yc);ih;){var Ec=32;var Ke=yd;do{yd=Ke;var Qf=$d;Ke=Ec>>>5;Ec+=1;Ke=yd+Ke;if(yd>Id){ih=!1;break}$d=A(M(Tc,Ke),Yc);te=Pd+pd[Qf];
pd[Qf]=yd-Pd}while(!Ga(Tc,yd,te));if(!ih)break;gd=Wa(Tc,Ud,yd-Ud,Rg,gd);do{Ec=yd;for(Ud=4;yd+Ud<td&&Tc[yd+Ud]===Tc[te+Ud];)Ud+=1;yd+=Ud;Qf=Ec-te;for(Ec=Rg;68<=Ud;)gd=xb(Ec,gd,Qf,64),Ud-=64;64<Ud&&(gd=xb(Ec,gd,Qf,60),Ud-=60);gd=xb(Ec,gd,Qf,Ud);Ud=yd;if(yd>=Id){ih=!1;break}te=A(M(Tc,yd-1),Yc);pd[te]=yd-1-Pd;Ec=A(M(Tc,yd),Yc);te=Pd+pd[Ec];pd[Ec]=yd-Pd}while(Ga(Tc,yd,te));if(!ih)break;yd+=1;$d=A(M(Tc,yd),Yc)}Ud<td&&(gd=Wa(Tc,Ud,td-Ud,Rg,gd));Yc=gd;xd+=Gd}return Yc};K.Vi=Nb}}),ed="undefined"!==typeof window?
window:self,Rc="undefined"!==typeof window?window:self,zc=self,hd=setTimeout;W.prototype["catch"]=function(K){return this.then(null,K)};W.prototype.then=function(K,A){var M=new this.constructor(N);fa(this,new B(K,A,M));return M};W.prototype["finally"]=function(K){var A=this.constructor;return this.then(function(M){return A.resolve(K()).then(function(){return M})},function(M){return A.resolve(K()).then(function(){return A.reject(M)})})};W.all=function(K){return new W(function(A,M){function Ga(Xb,cc){try{if(cc&&
("object"===typeof cc||"function"===typeof cc)){var dc=cc.then;if("function"===typeof dc){dc.call(cc,function(Dc){Ga(Xb,Dc)},M);return}}Wa[Xb]=cc;0===--xb&&A(Wa)}catch(Dc){M(Dc)}}if(!K||"undefined"===typeof K.length)return M(new TypeError("Promise.all accepts an array"));var Wa=Array.prototype.slice.call(K);if(0===Wa.length)return A([]);for(var xb=Wa.length,Nb=0;Nb<Wa.length;Nb++)Ga(Nb,Wa[Nb])})};W.allSettled=function(K){return new this(function(A,M){function Ga(Nb,Xb){if(Xb&&("object"===typeof Xb||
"function"===typeof Xb)){var cc=Xb.then;if("function"===typeof cc){cc.call(Xb,function(dc){Ga(Nb,dc)},function(dc){Wa[Nb]={status:"rejected",reason:dc};0===--xb&&A(Wa)});return}}Wa[Nb]={status:"fulfilled",value:Xb};0===--xb&&A(Wa)}if(!K||"undefined"===typeof K.length)return M(new TypeError(typeof K+" "+K+" is not iterable(cannot read property Symbol(Symbol.iterator))"));var Wa=Array.prototype.slice.call(K);if(0===Wa.length)return A([]);var xb=Wa.length;for(M=0;M<Wa.length;M++)Ga(M,Wa[M])})};W.resolve=
function(K){return K&&"object"===typeof K&&K.constructor===W?K:new W(function(A){A(K)})};W.reject=function(K){return new W(function(A,M){M(K)})};W.race=function(K){return new W(function(A,M){if(!K||"undefined"===typeof K.length)return M(new TypeError("Promise.race accepts an array"));for(var Ga=0,Wa=K.length;Ga<Wa;Ga++)W.resolve(K[Ga]).then(A,M)})};W.Kb="function"===typeof setImmediate&&function(K){setImmediate(K)}||function(K){hd(K,0)};W.Rc=function(K){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",
K)};var ad=function(){function K(A){var M=A.id;M=void 0===M?void 0:M;var Ga=A.da,Wa=A.query;A=A.result;M?this.id=M:(K.Wf++,this.id=K.Wf);this.da=Ga;this.query=Wa;this.result=void 0===A?void 0:A}K.decode=function(A){try{if("DT UI Worker Bridge"===A.type){var M=A.payload;return new K({id:M.id,da:M.handler,query:M.query,result:M.result})}}catch(Ga){}};K.prototype.Kh=function(A){"undefined"===typeof A?this.result=null:this.result=A};K.prototype.Na=function(){return{type:"DT UI Worker Bridge",payload:{id:this.id,
handler:this.da,query:this.query,result:this.result}}};K.Wf=0;return K}(),Oc=function(){function K(A){A?this.port=A:(A=new MessageChannel,this.port=A.port1,this.Eh=A.port2)}K.Hf=function(){K.ud||(K.ud=new Map)};K.oe=function(A,M){K.Hf();var Ga=K.ud.get(A);if(Ga)Ga.push(M);else{var Wa=[M];K.ud.set(A,Wa);A.addEventListener("message",function(xb){var Nb=ad.decode(xb.data);Nb&&Wa.forEach(function(Xb){Xb(Nb,xb,function(){K.Ze(A,M)})})})}return M};K.Ze=function(A,M){K.Hf();A=K.ud.get(A)||[];A.splice(A.indexOf(M),
1)};K.Pc=function(A,M,Ga){var Wa=void 0===Ga?{}:Ga;Ga=Wa.origin;Ga=void 0===Ga?"*":Ga;Wa=Wa.gf;Wa=void 0===Wa?[]:Wa;M=M.Na();S()||-1<Object.prototype.toString.call(A).indexOf("Worker")?A.postMessage(M,Wa):A.postMessage(M,Ga,Wa)};K.prototype.Mc=function(A){this.port.onmessage=function(M){(M=ad.decode(M.data))&&A(M)}};K.prototype.send=function(A,M){void 0===M&&(M=[]);this.port.postMessage(A.Na(),M)};return K}(),Vc,Fc=0,ae,Qc,Ic,Sc,ec=[],Cc=new Map,bd=new Map,he=[],Me=self.performance||Date,fd=Date.now()-
Me.now(),pe=function(K,A,M){return M=null!=K?Ma(Hb(K)):{},ab(!A&&K&&K.Ak?M:Eb(M,"default",{value:K,enumerable:!0}),K)}(lc()),we=[[/\u0000/g,"\x00"],[/\u0001/g,"\u0001"],[/\u0002/g,"\u0002"],[/\u0003/g,"\u0003"],[/\u0014/g,"\u0014"],[/\u0004/g,"\u0004"],[/\u0005/g,"\u0005"],[/\u0006/g,"\u0006"],[/\u0011/g,"\u0011"],[/\u0012/g,"\u0012"]],qe,be,hf=0,Ae,Pe,De,pf=!1,Be,nf=function(){function K(){this.nc=[];this.values=[]}K.prototype.add=function(A,M){this.nc[this.nc.length-1]===M&&(this.nc.pop(),this.values.pop());
this.dd()!==A&&(this.nc.push(M),this.values.push(A))};K.prototype.Ve=function(){return this.nc.length?this.nc[this.nc.length-1]:0};K.prototype.dd=function(){return this.values.length?this.values[this.values.length-1]:null};K.prototype.clear=function(A){var M=-1;this.nc.forEach(function(Ga,Wa){Ga<A&&(M=Wa)});0<M&&(this.values=this.values.slice(M),this.nc=this.nc.slice(M))};K.prototype.find=function(A,M,Ga){void 0===M&&(M=0);void 0===Ga&&(Ga=!1);var Wa=A.from,xb=A.Dg,Nb={ef:[],values:[]},Xb=-1,cc=this.dj();
this.nc.forEach(function(dc,Dc){var xd=cc({time:dc,index:Dc,Vj:M,from:Wa,Dg:xb});xd&&(Nb.ef.push(xd.time),Nb.values.push(xd.value));Ga&&dc<Wa&&(Xb=Dc)});-1!==Xb&&(Nb.ef.unshift(this.nc[Xb]-Wa),Nb.values.unshift(this.values[Xb]));return Nb};K.prototype.dj=function(){var A=this;return function(M){return K.Si(A,M)}.bind(this)};K.Wi=function(A,M){return 0!==M&&"string"===typeof A&&A.length>M};K.Ui=function(A){return A.from<=A.time&&A.time<A.Dg};K.Si=function(A,M){A=A.values[M.index];return K.Ui(M)&&!K.Wi(A,
M.Vj)?{time:M.time-M.from,value:A}:null};return K}(),Td={matchesSelector:function(K,A){return ba(K)?(K.matches||K.matchesSelector||K.mozMatchesSelector||K.msMatchesSelector||K.oMatchesSelector||K.webkitMatchesSelector).call(K,A):!1}},t=["DATALIST","INPUT","TEXTAREA","SELECT","OPTION"],C=["submit","button","reset"],P="textarea input[type=text] input:not([type]) input[type=password] input[type=hidden] input[type=checkbox] input[type=radio] input[type=date] input[type=month] input[type=week] input[type=datetime-local] input[type=time] input[type=number] input[type=range] input[type=file] input[type=email] input[type=url] input[type=tel] input[type=search] select option".split(" "),
ma,oa,Ja,Za,db,ub,Jb=function(){function K(A,M){this.fg=A;this.Gf=M}K.prototype.ve=function(A){var M=this;return this.Gf.some(function(Ga){return M.fg.matchesSelector(A,Ga.Ra())})};K.prototype.Le=function(A){var M=this;return this.Gf.some(function(Ga){return M.fg.matchesSelector(A,Ga.Ra())&&Ga.Le()})};return K}(),fc=function(){function K(A){this.Wg=A}K.prototype.ve=function(A){return this.Wg.some(function(M){return M.Ra().test(A)})};return K}(),gc=function(){function K(A,M,Ga,Wa){void 0===Wa&&(Wa=
new WeakMap);this.Ff=A;this.Vg=M;this.Ta=Ga;this.pd=Wa}K.prototype.Ob=function(A){if(Ya(A)||Ya(A.parentNode))return 1;var M=this.Ta?1:2,Ga=ba(A)&&A.hasAttribute("data-dtrum-mask"),Wa=this.Ff.ve(A);Ga?M=10:Wa&&(M=this.Ta?this.bh(A):1);var xb=this.pd.get(A.parentNode),Nb=Ga;xb&&(Ga=this.eh(xb,M,Ga||Wa),M=Ga.uh,Nb=Nb||Ga.Ce);this.Ih(A,M,Nb);return M};K.prototype.Ue=function(A,M){var Ga=this.Ta?1:16;return-1!==["value","placeholder","label"].indexOf(M)?this.dh(A,M):this.mh(M)||!this.lh(M)?1:this.Vg.ve(M)?
this.Ta?16:1:(A=this.pd.get(A))?(Ga=this.Ta?A.Zd:A.Yd,2===(Ga&2)?16:Ga):Ga};K.prototype.eh=function(A,M,Ga){var Wa=!1;A.Ce?(M=10,Wa=!0):(A=this.Ta?A.Zd:A.Yd,Ga||(M=A),this.Ta&&(M|=A));return{uh:M,Ce:Wa}};K.prototype.Ih=function(A,M,Ga){Ga={Ce:Ga};var Wa=this.pd.get(A);this.Ta?Ga.Zd=(Wa&&Wa.Zd)|M:Ga.Yd=(Wa&&Wa.Yd)|M;Wa&&(Ga=bb(bb({},Wa),Ga));this.pd.set(A,Ga)};K.prototype.bh=function(A){var M=2;this.Ff.Le(A)&&(M|=8);return M};K.prototype.lh=function(A){return/^data(-.*)?$/.test(A)};K.prototype.mh=
function(A){return/^data-dt-(.+)$/.test(A)};K.prototype.dh=function(A,M){return ta(A)&&"value"===M?32:2===(this.Ob(A)&2)?16:1};return K}(),qd=function(){function K(A){this.value=A}K.kh=function(A){return A instanceof K};K.prototype.Ra=function(){return this.value};return K}(),id=function(){function K(A){this.ag=!1;A=A.split(K.jf);var M=A[1];this.value=A[0];this.ag=""===M}K.oh=function(A){return A instanceof K};K.prototype.Ra=function(){return this.value};K.prototype.Le=function(){return this.ag};
K.jf="&";return K}(),Dd=function(){function K(A){this.zh=A}K.create=function(A){return new K(A)};K.prototype.Ra=function(){return this.zh};return K}(),ld=function(){function K(A){this.Ah=A}K.create=function(A){return new K(A)};K.prototype.Ra=function(){return this.Ah};return K}(),Ee=function(){function K(A,M,Ga){void 0===A&&ld.create(2);void 0===M&&(M=Dd.create(0));void 0===Ga&&(Ga=[]);this.yh=M;this.rules=Ga}K.prototype.hh=function(){return this.rules.filter(id.oh)};K.prototype.fh=function(){return this.rules.filter(qd.kh)};
K.prototype.addRule=function(A){this.rules.push(A)};K.prototype.Ta=function(){return 0===this.yh.Ra()};return K}(),Ze=function(){function K(){}K.create=function(A,M){if(!K.validate(M))throw Error("Invalid masking rule value: "+M+"!");switch(A){case 0:return new id(M);case 1:return new qd(new RegExp(M));default:throw Error("Invalid masking rule type: "+A+"!");}};K.validate=function(A){return A&&""!==A.trim()};return K}();(function(){function K(A){var M=this;this.se=[];this.th=new WeakMap;Array.isArray(A)?
A.forEach(function(Ga){M.Xf(Ga)}):this.Xf(A)}K.prototype.Xf=function(A){var M;A=A.split(",");2===Number(A[0])?M={te:A.slice(0,4).join(",")}:M={vh:A.slice(0,5).join(","),te:A.slice(5,9).join(",")};if(M.te){A=M.te.split(",").map(decodeURIComponent);var Ga=A[2];M=A[3];A=ld.create(Number(A[1]));Ga=Dd.create(Number(Ga));M=za(M?M.split(";"):[]);M=new Ee(A,Ga,M)}else M=ea(M.vh);M instanceof Ee?(A=new Jb(Td,M.hh()),Ga=new fc(M.fh()),M=new gc(A,Ga,M.Ta(),this.th),this.se.push(M)):(M=this.ue=M,oa=new WeakMap,
Ja=new WeakMap,Za=new WeakMap,db=new WeakMap,ub=new WeakMap,ma=M,La(ma.Ec,oa),La(ma.zc,Ja),La(ma.Kc,Za))};K.prototype.Ob=function(A){if(this.ue)return cb(A);for(var M,Ga=0,Wa=this.se;Ga<Wa.length;Ga++){var xb=Wa[Ga].Ob(A);1!==xb&&(M|=xb)}return M||1};K.prototype.Ue=function(A,M){if(this.ue)return $a(A,M);for(var Ga,Wa=0,xb=this.se;Wa<xb.length;Wa++){var Nb=xb[Wa].Ue(A,M);1!==Nb&&(Ga|=Nb)}return Ga||1};return K})();var Ne=function(){function K(A,M){this.name=A.attributeName||"";this.values=new nf;
this.wa=A.wa;this.$c=M;this.Gi=A.ga;this.yg(A.vb,M)}K.prototype.Ra=function(){return this.values.dd()};K.prototype.yg=function(A,M){var Ga=Ia(this.Gi);Ga&&"a"===Ga.name&&"href"===this.name&&(A="");"string"===typeof A&&(A=this.Tj(A));this.Ra()!==A&&(this.values.add(A,M),this.$c=M,Ga&&(Ga.sc(A),Ga.sc(M)))};K.prototype.Tj=function(A){var M,Ga=Ia(this.Gi),Wa="value"===this.name&&"input"===(null===Ga||void 0===Ga?void 0:Ga.name)&&"number"===(null===(M=null===Ga||void 0===Ga?void 0:Ga.getAttribute("type"))||
void 0===M?void 0:M.Ra())?"0":"*";this.wa&&this.wa&32?A=A?A.replace(/./g,"*"):"":this.wa&&this.wa&16&&(A=Y(A,Wa));M=Ga&&Ga.wa&&Ga.wa&2;if(M=(Ga&&Ga.wa&&Ga.wa&4||M)&&Ga){var xb=this.name,Nb;M=X(["input","textarea"],null===(Nb=Ga.name)||void 0===Nb?void 0:Nb.toLowerCase())&&"value"===xb}M&&(A=Y(A,Wa));return A};return K}(),tg=Date.prototype.toJSON,uf=function(){function K(A,M){if(!A||!M)throw Ua("Invalid parameters for mutation construction",{type:A,Hi:M}),Error("Invalid parameters");this.type=A;this.ga=
M.ga;this.nodeName=M.nodeName;this.namespaceURI=M.namespaceURI;this.nodeValue=M.nodeValue;this.attributeName=M.attributeName;this.vb=M.vb;this.va=M.va;this.xa=M.xa;this.Ba=M.Ba;this.wa=M.wa}K.decode=function(A){try{var M=JSON.parse(A);return new K(M.type,{ga:M.nodeId,nodeName:M.nodeName,namespaceURI:M.namespaceURI,nodeValue:M.nodeValue,attributeName:M.attributeName,vb:M.attributeValue,va:M.parentId,xa:M.previousId,Ba:M.nextId,wa:M.masking})}catch(Ga){return null}};K.prototype.Na=function(){return hb({type:this.type,
nodeId:this.ga,nodeName:this.nodeName,namespaceURI:this.namespaceURI,nodeValue:this.nodeValue,attributeName:this.attributeName,attributeValue:this.vb,parentId:this.va,previousId:this.xa,nextId:this.Ba,masking:this.wa})};K.prototype.Qg=function(){};K.Yh="updateNode";return K}(),Rf=/(,?(\b|\s|\.|#)ng):((?!(a(ctive|ny(-link)*)|checked|d(efault|i(r\(.*\)|sabled))|e(mpty|nabled)|f(irst(-(child|of-type))*|ullscreen|ocus)|hover|in(determinate|valid|-range)|la(ng\(.*\)|(st-(child|of-type)))|l(eft|ink)|n(ot\(.*\)|th-((last-)*(child|of-type)\(.*\)))|o(nly-(child|of-type)|ptional|ut-of-range)|r(e(ad-(only|write)|quired)|ight|oot)|scope|target|v(alid|isited)))[^,\[\]]*\s*.*(,|{).*)/,
li=function(){function K(A,M){this.id=A.ga;this.name=A.nodeName;this.Ig=M;this.id&&"1"===this.id.split(".").pop()&&(this.yi=M-1,-1===he.indexOf(this)&&he.push(this));this.attributes=new Map;this.values=new nf;this.Od=new nf;this.od=new nf;this.Ng=new nf;this.Lf=new nf;this.$c=this.Ig;this.uf=0;this.wa=A.wa;this.id&&this.name&&(this.Hg=this.id.toString().length+1+this.name.toString().length+1);switch(A.namespaceURI){case "http://www.w3.org/2000/svg":this.type="svg";break;case "http://www.w3.org/1998/Math/MathML":this.type=
"mathml";break;case "dynatrace-metadata":this.type="dtmeta";break;case "css-stylesheet":this.type="cssstylesheet";break;default:this.type="html"}this.Og(A.va,M);this.wd(A.xa,M);this.vd(A.Ba,M);"string"===typeof A.nodeValue&&this.yg(A.nodeValue,M);this.id&&A.va&&this.he(this.getParent())&&!A.xa&&this.he(this.getParent()).Jh(this.id,M);"html"!==this.type&&this.sc(this.type)}K.prototype.he=function(A){return Ia(A)};K.prototype.Ug=function(A){if(!this.attributes.has(A.name)){var M=this.wa&&this.wa&2;
if(M=this.wa&&this.wa&4||M){M=A.name;var Ga,Wa=this.name||"";M="selected"===M&&"option"===Wa.toLowerCase()?!0:"checked"===M&&"input"===Wa.toLowerCase()?X(["radio","checkbox"],null===(Ga=this.getAttribute("type"))||void 0===Ga?void 0:Ga.Ra()):!1}if(M){A=A.$c;var xb;A=new Ne(new uf("updateAttribute",{attributeName:"disabled",vb:"",wa:1,ga:this.id}),A);"input"===(null===(xb=this.name)||void 0===xb?void 0:xb.toLowerCase())?this.Ug(A):(xb=this.he(this.getParent()),Ga=(null===xb||void 0===xb?void 0:xb.name)||
"",xb&&"optgroup"===Ga.toLowerCase()&&(xb=xb.he(xb.getParent()),Ga=(null===xb||void 0===xb?void 0:xb.name)||""),xb&&"select"===Ga.toLowerCase()&&xb.Ug(A))}else this.attributes.set(A.name,A),this.$h(A),this.sc(A.name)}};K.prototype.getAttribute=function(A){return this.attributes.get(A)};K.prototype.Ne=function(A){void 0!==A&&(this.$c=Math.max(A,this.$c),(A=this.he(this.getParent()))&&A.Ne(this.$c))};K.prototype.$h=function(A){this.uf=Math.max(this.uf,A.$c);this.Ne(this.uf)};K.prototype.Ra=function(){return this.values.dd()};
K.prototype.yg=function(A,M){this.wa&&this.wa&2&&(A=Y(A));if("#text"===this.name&&pf){var Ga=this.he(this.getParent());if(Ga&&"style"===Ga.name&&(!A||-1!==A.indexOf("ng:")))for(;Rf.test(A);)A=A.replace(Rf,"$1\\:$3")}this.Ra()!==A&&(this.values.add(A,M),this.Ne(M),this.sc(A),this.sc(M))};K.prototype.getParent=function(){return this.Od.dd()};K.prototype.Og=function(A,M){this.getParent()!==A&&(this.Od.add(A,M),this.Ne(M),this.sc(A),this.sc(M))};K.prototype.ri=function(){return this.Ng.dd()};K.prototype.wd=
function(A,M){this.ri()!==A&&(this.Ng.add(A,M),this.Ne(M),this.sc(A),this.sc(M))};K.prototype.oi=function(){return this.od.dd()};K.prototype.vd=function(A,M){this.oi()!==A&&(this.od.add(A,M),this.Ne(M))};K.prototype.xj=function(){return this.Lf.dd()};K.prototype.Jh=function(A,M){this.xj()!==A&&(this.Lf.add(A,M),this.Ne(M))};K.prototype.Zj=function(){this.Hg=0};K.prototype.sc=function(A){A="string"===typeof A?A:"number"===typeof A?A.toString():null===A?"null":"";this.Hg+=A.length+1;var M=this.he(this.getParent());
M&&M.sc(A)};K.prototype.Aj=function(){return Math.max(this.uf,this.values.Ve(),this.Od.Ve(),this.Lf.Ve(),this.od.Ve(),this.Ng.Ve())};return K}(),Ff=function(){function K(A){this.time=A;this.set=[];this.time=A;this.size=this.set.length}K.decode=function(A){try{var M=JSON.parse(A);if(M&&"Mutation List"===M.type){var Ga=M.payload,Wa=new K(Ga.time);A=0;for(var xb=Ga.entries;A<xb.length;A++){var Nb=uf.decode(xb[A]);Nb&&Wa.add(Nb)}return Wa}}catch(Xb){}};K.Re=function(A,M){var Ga=new K(M);A.forEach(function(Wa){Ga.add(Wa)});
return Ga};K.prototype.add=function(A){A instanceof uf&&(this.set.push(A),this.size=this.set.length)};K.prototype.fi=function(A){this.set=this.set.filter(function(M){return M instanceof uf&&!A(M)});this.size=this.set.length};K.prototype.forEach=function(A){this.set.forEach(function(M){return M instanceof uf&&A(M)})};K.prototype.Na=function(){return hb({type:"Mutation List",payload:{time:this.time,entries:this.set.map(function(A){return A.Na()})}})};return K}(),Qe,Ye=(Qe={},Qe.addNode=function(K,A){var M=
new li(K,A);Cc.set(K.ga,M);if(X(["dynatrace-metadata","css-stylesheet"],K.namespaceURI)&&void 0===K.va)bd.set(M.id,M);else{M=Ia(K.xa);var Ga=Ia(K.Ba);M&&M.vd(K.ga,A);Ga&&Ga.wd(K.ga,A)}},Qe.updateNode=function(K,A){var M=Ia(K.ga),Ga=Ia(K.va),Wa=Ia(K.Ba),xb=Ia(K.xa);M&&M.id&&(Ga&&M.Og(Ga.id,A),xb?(xb.vd(M.id,A),M.wd(K.xa,A)):Ga&&Ga.Jh(M.id,A),Wa&&(Wa.wd(M.id,A),M.vd(K.Ba,A)),M.vd(K.Ba,A),M.wd(K.xa,A))},Qe.removeNode=function(K,A){if((K=Ia(K.ga))&&K.id){var M=Ia(K.getParent()),Ga=Ia(K.oi()),Wa=Ia(K.ri());
Wa&&Ga?(Wa.vd(Ga.id,A),Ga.wd(Wa.id,A)):Wa?Wa.vd(null,A):(Ga&&Ga.wd(null,A),M&&M.Jh(Ga?Ga.id:null,A));K.Og(null,A);K.vd(null,A);K.wd(null,A)}},Qe.updateNodeValue=function(K,A){var M=Ia(K.ga);M&&K.nodeValue&&M.yg(K.nodeValue,A)},Qe.updateAttribute=function(K,A){var M=Ia(K.ga);if(void 0!==M&&K.attributeName){var Ga=M.getAttribute(K.attributeName);"undefined"===typeof Ga?(Ga=new Ne(K,A),M.Ug(Ga)):(Ga.yg(K.vb,A),M.$h(Ga))}},Qe),vb=new Uint32Array([1116352408,1899447441,3049323471,3921009573,961987163,
1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,
958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298]),fe=function(){function K(){this.pj=32;this.blockSize=64;this.state=new Int32Array(8);this.Oh=new Int32Array(64);this.buffer=new Uint8Array(128);this.Gg=this.Bd=0;this.finished=!1;this.reset()}K.prototype.reset=function(){this.state[0]=1779033703;this.state[1]=3144134277;this.state[2]=1013904242;this.state[3]=2773480762;this.state[4]=1359893119;this.state[5]=2600822924;
this.state[6]=528734635;this.state[7]=1541459225;this.Gg=this.Bd=0;this.finished=!1;return this};K.prototype.update=function(A,M){void 0===M&&(M=A.length);if(this.finished)throw Error("SHA256: can't update because hash was finished.");var Ga=0;this.Gg+=M;if(0<this.Bd){for(;64>this.Bd&&0<M;)this.buffer[this.Bd++]=A[Ga++],M--;64===this.Bd&&($b(this.Oh,this.state,this.buffer,0,64),this.Bd=0)}64<=M&&(Ga=$b(this.Oh,this.state,A,Ga,M),M%=64);for(;0<M;)this.buffer[this.Bd++]=A[Ga++],M--;return this};K.prototype.finish=
function(A){if(!this.finished){var M=this.Gg,Ga=this.Bd,Wa=M/536870912|0,xb=M<<3;M=56>M%64?64:128;this.buffer[Ga]=128;for(Ga+=1;Ga<M-8;Ga++)this.buffer[Ga]=0;this.buffer[M-8]=Wa>>>24&255;this.buffer[M-7]=Wa>>>16&255;this.buffer[M-6]=Wa>>>8&255;this.buffer[M-5]=Wa>>>0&255;this.buffer[M-4]=xb>>>24&255;this.buffer[M-3]=xb>>>16&255;this.buffer[M-2]=xb>>>8&255;this.buffer[M-1]=xb>>>0&255;$b(this.Oh,this.state,this.buffer,0,M);this.finished=!0}for(Ga=0;8>Ga;Ga++)A[4*Ga]=this.state[Ga]>>>24&255,A[4*Ga+1]=
this.state[Ga]>>>16&255,A[4*Ga+2]=this.state[Ga]>>>8&255,A[4*Ga+3]=this.state[Ga]>>>0&255;return this};K.prototype.digest=function(){var A=new Uint8Array(this.pj);this.finish(A);return A};return K}();(function(){function K(){}K.bk=function(){var A;void 0===A&&(A=W);Oa||(Oa=A)};return K})().bk();(function(){return ya(this,void 0,void 0,function(){return eb(this,function(K){switch(K.label){case 0:return S()?[4,ka()]:[3,2];case 1:return K.J(),[3,3];case 2:qa(),K.label=3;case 3:return[2]}})})})()})();
